Add example folder with example config file and output
BESTenergytrade/simply pull request #110
Opened 2022-06-02 10:42 UTC by dog-ball

Fixes #36

2022-06-02 12:04 UTC, j-ti requested changes
see comments

2022-06-02 12:04 UTC, j-ti commented on examples/example_scenario/matches.csv
> +10.0,4,3,H4,H3,1,0,0.2,0.08884487582548159,0.010000000000000009
Will be overridden -> rename for validation

2022-06-02 12:04 UTC, j-ti commented on examples/example_scenario/orders.csv
> +-1.0,10,H4,1,0.4,0.16249843482194495
Will be overridden -> rename for validation

2022-06-14 10:11 UTC, dog-ball commented
I have renamed the example scenario to validation scenario so it is no longer overwritten when the example config file is run. Maybe I should reference the examples folder in the documentation so people understand its use?

2022-06-14 16:27 UTC, j-ti requested changes
with the example config only matches.csv and orders.csv get overridden by an execution, so a suffix to the file is sufficient rather than a new folder, the other files should stay in example_scenario while the config already guarantees that they are not updated, i.e. `update_scenario = false`

2022-06-15 13:13 UTC, j-ti commented on examples/config_example.txt
> +# If orders should be saved, the market should not be reset
comment still exists

2022-06-16 13:19 UTC, merged