Gridfeedoc
BESTenergytrade/simply pull request #222
Opened 2024-04-17 12:24 UTC by bedirhankose

This pull request includes the document I added to the Grid Fee Matrix section of the Simply Simulation documentation. 

1. Added an example table to clearly illustrate the structure of the grid fee matrix.
2. Provided detailed explanations under two main headings for entering the grid fee matrix.
3. Added an example grid fee matrix definition in JSON format.
4. Clearly outlined the method to construct a grid fee matrix from configuration files.
5. Added sample entries for the configuration file.
6. Included a conclusion section at the end of the document.

2024-04-17 16:20 UTC, j-ti requested changes
Some remarks in comments

2024-04-17 16:20 UTC, j-ti commented on doc/source/matching_strategies.rst
> +There are two primary methods to input a grid fee matrix into the Simply Simulation:
```suggestion
There are two methods to define a grid fee matrix for the simply simulation:
```

2024-04-17 16:20 UTC, j-ti commented on doc/source/matching_strategies.rst
> +- The weight factor describes the relationship between grid fee and cumulative power network edge weights.
```suggestion
- The weight factor describes the relationship between grid fee and cumulative power network edge weight between two nodes in the network. The cumulative weight is the sum of all edge weights along the shortest path in the network between those nodes. If there are multiple nodes per cluster, nodes of one cluster have equivalent cumulative weights to all nodes of of another cluster.
```

2024-04-17 16:20 UTC, j-ti commented on doc/source/matching_strategies.rst
> +   }
Where can I find this in the code? Is it in another branch?

2024-04-17 16:20 UTC, j-ti commented on doc/source/matching_strategies.rst
> +""""""""""""""""""""""""""""""
not visible

2024-04-17 16:20 UTC, j-ti commented on doc/source/matching_strategies.rst
> +
too many section, does not look very compact, maybe try
- `**Format**: The grid fee matrix should be provided in a structured format such as JSON or CSV.` etc.
- or as a two column table

2024-04-17 16:20 UTC, j-ti commented on doc/source/matching_strategies.rst
> +- ``weight_factor``: Factor describing the relationship of grid fee to cumulative power network edge weights.
```suggestion
- ``default_grid_fee``: Default grid fee applied for trades with the market maker
- ``local_grid_fee``: Local grid fee applied for trades within a cluster
- ``weight_factor``: Factor describing the relationship of grid fee to cumulative power network edge weights (see description above)
```

2024-04-17 16:20 UTC, j-ti commented on doc/source/matching_strategies.rst
> +Entering a grid fee matrix into a simulation is essential for accurate cost calculations related to using the grid. Ensure proper format, identifiers, units, and values for the rate matrix, whether c
This description should stand in the beginning, e.g. after line 52

2024-04-17 16:20 UTC, j-ti commented on doc/source/matching_strategies.rst
> +2. Use these values to calculate or define the grid fee matrix entries.
This is happening within simply, steps do not need to be explained, and parameter are explained above
can be removed

2024-04-17 16:20 UTC, j-ti commented on doc/source/matching_strategies.rst
> +2. Building a Grid Fee Matrix from Configuration Files
maybe here reference links to the subsections below could be used

2024-04-23 06:49 UTC, bedirhankose commented on doc/source/matching_strategies.rst
> +   }
I created this as an example.

2024-04-30 09:17 UTC, closed without merging